### ISSUE TITLE
Creating a new Conversation using CLI should return Chat Service SID

### ISSUE THREAD

**Issue by LuceCarter** [twilio/twilio-cli#102]
The Conversations Quickstart guide suggests the following command for creating a conversation using the CLI
```
twilio api:conversations:v1:conversations:create \
--friendly-name "My First Conversation"
```

However the response back when running this command doesn't including the Chat Service SID which the guide asks you to copy and I believe it should.

**Comment by childish-sambino** [comment]
Agreed, it should be included by default. Note that adding the option `-o json` shows all the returned properties.

I've submitted the change internally and it should get picked up in the next release.

**Comment by LuceCarter** [comment]
Thanks for the tip :) And thanks for handling it so quickly!

**Comment by thinkingserious** [comment]
Release is live, thanks for your patience!
