### ISSUE TITLE
CLI error for "twilio phone-numbers:update"

### ISSUE THREAD

**Issue by akira75** [twilio/twilio-cli#104]
#### Issue Summary

 Issue the command "twilio phone-numbers:update +19725971750"

#### Steps to Reproduce

(venv) Albertos-MBP:Quest albertokiramoto$ twilio phone-numbers:update +19725971750
 » twilio-cli encountered an unexpected error. To report this issue, execute the command with the "-l debug" flag, then copy the output to a new issue here: https://github.com/twilio/twilio-cli/issues
(venv) Albertos-MBP:Quest albertokiramoto$ twilio phone-numbers:update +19725971750 -l debug
[DEBUG] Config File: /Users/albertokiramoto/.twilio-cli/config.json
[DEBUG] Using profile: ${TWILIO_ACCOUNT_SID}/${TWILIO_AUTH_TOKEN}
[DEBUG] -- BEGIN Twilio API Request --
[DEBUG] GET https://api.twilio.com/2010-04-01/Accounts/AC95a01d3c0c4515d73c9597e6a529e8c5/IncomingPhoneNumbers.json
[DEBUG] Querystring:
[DEBUG] {"PhoneNumber":"+19725971750"}
[DEBUG] User-Agent: @twilio/cli-core/3.0.2 (twilio-node/3.33.3, node.js v10.16.0, darwin 18.7.0 x64, phone-numbers:update)
[DEBUG] -- END Twilio API Request --
[DEBUG] response.statusCode: 200
[DEBUG] response.headers: {"date":"Sat, 17 Aug 2019 02:30:03 GMT","content-type":"application/json; charset=utf-8","content-length":"1857","connection":"close","twilio-concurrent-requests":"1","twilio-request-id":"RQ1533c2f1063d4d49b58aaad23effc241","twilio-request-duration":"0.131","access-control-allow-origin":"*","access-control-allow-headers":"Accept, Authorization, Content-Type, If-Match, If-Modified-Since, If-None-Match, If-Unmodified-Since","access-control-allow-methods":"GET, POST, DELETE, OPTIONS","access-control-expose-headers":"ETag","access-control-allow-credentials":"true","x-powered-by":"AT-5000","x-shenanigans":"none","x-home-region":"us1","x-api-domain":"api.twilio.com","strict-transport-security":"max-age=31536000"}
 » twilio-cli encountered an unexpected error. To report this issue, execute the command with the "-l debug" flag, then copy the output to a new issue here: https://github.com/twilio/twilio-cli/issues
[DEBUG] Cannot read property 'smsUrl' of null
[DEBUG] TypeError: Cannot read property 'smsUrl' of null
    at NumberUpdate.isLocalhostUrl (/usr/local/Cellar/twilio/1.4.1/libexec/src/commands/phone-numbers/update.js:55:14)
    at NumberUpdate.UrlFlags.filter.propName (/usr/local/Cellar/twilio/1.4.1/libexec/src/commands/phone-numbers/update.js:21:74)
    at Array.filter (<anonymous>)
    at NumberUpdate.runCommand (/usr/local/Cellar/twilio/1.4.1/libexec/src/commands/phone-numbers/update.js:21:50)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(venv) Albertos-MBP:Quest albertokiramoto$

**Comment by childish-sambino** [comment]
Yup, I’ve seen this before. Need to provide some flag to update the phone number with. Otherwise it’s a no-op (CLI still shouldn’t bug out though).
