### ISSUE TITLE
Retrieve plug-ins available for installation using CLI

### ISSUE THREAD

**Issue by pranavdesh** [twilio/twilio-cli#117]
Would be great to have a top level CLI command to list all available plug-ins.

**Comment by thinkingserious** [comment]
Hello @pranavdesh,

Thank you for the suggestion!

This issue has been added to our internal backlog to be prioritized. Pull requests and +1s on the issue summary will help it move up the backlog.

With best regards,

Elmer

**Comment by childish-sambino** [comment]
PR submitted.
