### ISSUE TITLE
twilio-cli stuck on getting it work. problem with  No such interface ?org.freedesktop.Secret.Collection? on object at path /org/freedesktop/secrets/collection/login

### ISSUE THREAD

**Issue by BothOfUsTogether2** [twilio/twilio-cli#123]
#### Issue Summary

A summary of the issue and the environment in which it occurs. If suitable, include the steps required to reproduce the bug. Please feel free to include screenshots, screencasts, code examples.

im ssh to my raspberry pi locally and trying to use twilio cli. i installed so much packages: dbus, dbus-x11, gnome-keyring and more. No matter how many error I resolve there is another error and I am stuck!

This is the error:

** Message: 04:54:16.449: Remote error from secret service: org.freedesktop.DBus.Error.UnknownMethod: No such interface ?org.freedesktop.Secret.Collection? on object at path /org/freedesktop/secrets/collection/login
 » twilio-cli encountered an unexpected error. To report this issue, execute the command with the "-l debug" flag, then copy the output to a new issue here: https://github.com/twilio/twilio-cli/issues
[DEBUG] No such interface “org.freedesktop.Secret.Collection” on object at path /org/freedesktop/secrets/collection/login
[DEBUG] Error: No such interface “org.freedesktop.Secret.Collection” on object at path /org/freedesktop/secrets/collection/login

* twilio-cli Version: twilio-cli/1.6.1 linux-arm node-v10.16.3
* Node.js Version: v10.16.3

uname -m : armv6l
Raspbian 10

Is there a way to make it work or I just wasted my time for nothing?

**Comment by childish-sambino** [comment]
Not sure which command you’re attempting. Guessing it’s login and there’s no key ring support on the OS. Do env vars work for credentials?

**Comment by BothOfUsTogether2** [comment]
> Not sure which command you’re attempting. Guessing it’s login and there’s no key ring support on the OS. Do env vars work for credentials?

I installed gnome-keyring. I am on Raspbian OS.
Can you elaborate about env vars? I don't know what do you mean

**Comment by childish-sambino** [comment]
https://www.twilio.com/docs/twilio-cli/general-usage#want-to-use-environment-variables-instead-of-creating-a-profile

**Comment by BothOfUsTogether2** [comment]
> https://www.twilio.com/docs/twilio-cli/general-usage#want-to-use-environment-variables-instead-of-creating-a-profile

it's not clear:

1. TWILIO_ACCOUNT_SID - from account dashboard. right?
2. TWILIO_API_KEY - where do i find it? When i create api key i only see the secret.
3. TWILIO_API_SECRET - found it when i created the api key...

**Comment by BothOfUsTogether2** [comment]
@childish-sambino

**Comment by childish-sambino** [comment]
When using the env vars, you don't need to run the login command. The env vars will be used for auth instead of the profile that login attempts to create.

So, after exporting you can run twilio commands to interact with your account.

**Comment by childish-sambino** [comment]
Leaving this open as an enhancement when keytar cannot be loaded. Something like: 
```
> Secure credential storage failed to load
> You can also use credentials stored in environment variables:
>   export TWILIO_ACCOUNT_SID=the-account-sid
>   export TWILIO_API_KEY=the-api-key
>   export TWILIO_API_SECRET=the-api-secrect
```

**Comment by BothOfUsTogether2** [comment]
it works but how do i save it ?

**Comment by childish-sambino** [comment]
You can add the export statements to your shell resource file. `~/.zshrc` or `~/.bashrc` for example.

**Comment by BothOfUsTogether2** [comment]
thanks i will close it
