### ISSUE TITLE
Error: Cannot autolaunch D-Bus without X11 $DISPLAY

### ISSUE THREAD

**Issue by mjqPauli** [twilio/twilio-cli#137]
#### Issue Summary

A summary of the issue and the environment in which it occurs. If suitable, include the steps required to reproduce the bug. Please feel free to include screenshots, screencasts, or code examples.

#### Steps to Reproduce

1. This is the first step
2. This is the second step
3. Further steps, etc.

Any other information you want to share that is relevant to the issue being reported. Especially, why do you consider this to be a bug? What do you expect to happen instead?

#### Technical details:

* `twilio version` output: 
* Command output with debug logging enabled (adding `-l debug` to the end of the command):
```
output
```

**Comment by childish-sambino** [comment]
Could you provide details about the issue you’re having?
