### ISSUE TITLE
As a user, I should be prompted for my auth token when it is required, so that I can perform protected calls.

### ISSUE THREAD

**Issue by craigsdennis** [twilio/twilio-cli#146]
Certain API calls like `twilio api:core:keys:create` require the customer to provide an Auth Token.

The CLI does not persist the auth token, therefore what happens is the user receives the error:

> Error code 20003 from Twilio: Authenticate. See https://www.twilio.com/docs/errors/20003 for more info.

I would like to be prompted for my auth token if I encounter error `20003` when I am logged in to the CLI.

**Comment by childish-sambino** [comment]
This issue has been added to our internal backlog to be prioritized. Pull requests and +1s on the issue summary will help it move up the backlog.

**Comment by childish-sambino** [comment]
Working on a fix now. Going with the following wording when a 20003 is caught rather than a prompt which is a much more complicated change:
```
 » Error code 20003 from Twilio: Authenticate. See https://www.twilio.com/docs/errors/20003 for more info.

twilio-cli profiles use Standard API Keys which are not permitted to manage Accounts (e.g., create Subaccounts) and other API Keys. If you require this functionality, a Master API Key or Auth Token can be stored in environment variables:

# OPTION 1 (recommended)
export TWILIO_ACCOUNT_SID=your Account SID from twil.io/console
export TWILIO_API_KEY=an API Key created at twil.io/get-api-key
export TWILIO_API_SECRET=the secret for the API Key

# OPTION 2
export TWILIO_ACCOUNT_SID=your Account SID from twil.io/console
export TWILIO_AUTH_TOKEN=your Auth Token from twil.io/console
```
