### ISSUE TITLE
twilio could not get credentials for profile

### ISSUE THREAD

**Issue by jamesscaggs** [twilio/twilio-cli#147]
Steps to reproduce:

1. twilio profiles:add
2. provide friendlyname
3. provide account sid and auth token
4. twilio profiles:use friendlyname
5. twilio watch

Could not get credentials for profile "dev-dealerstack".
 » To reconfigure the profile, run: twilio profiles:add

Rinse and repeat and get the same issue

twilio-cli/1.9.2 darwin-x64 node-v12.14.0

**Comment by childish-sambino** [comment]
Can you check if you're using the latest version of the `watch` plugin (latest is _2.0.3_)? You can see plugin info using this command: `twilio plugins`

**Comment by jamesscaggs** [comment]
@childish-sambino Just updated versions and everything is working as expected. Thank you.

**Comment by elizabethsiegle** [comment]
@childish-sambino hi! I have the same error as @ jamesscaggs but when I run `twilio plugins` I get the error `Cannot read property 'dim' of undefined`

**Comment by childish-sambino** [comment]
@elizabethsiegle Fixed by https://github.com/twilio/twilio-cli/pull/172

Next release scheduled for 2020-04-29
