### ISSUE TITLE
Issue when trying to login

### ISSUE THREAD

**Issue by Lukario45** [twilio/twilio-cli#149]
Here is the output
`[lukario45@gen-mc ~]$ twilio login -l debug
[DEBUG] Config File: /home/lukario45/.twilio-cli/config.json
[DEBUG] Error loading keytar: Error: Cannot find module 'keytar'
Require stack:
- /usr/lib/node_modules/twilio-cli/node_modules/@twilio/cli-core/src/services/require-install.js
- /usr/lib/node_modules/twilio-cli/node_modules/@twilio/cli-core/src/base-commands/base-command.js
- /usr/lib/node_modules/twilio-cli/node_modules/@twilio/cli-core/src/index.js
- /usr/lib/node_modules/twilio-cli/bin/run
[DEBUG] Found command "login" plugin: twilio-cli
[DEBUG] Found keytar version in "@twilio/cli-core" dependencies: ^4.13.0
? Shorthand identifier for your profile: lukario45
You can find your Account SID and Auth Token at https://www.twilio.com/console
 » Your Auth Token will be used once to create an API Key for future CLI access to your Twilio Project, and then forgotten.
? The Account SID for your Twilio Project: AC40cd61a06e07ba0df9ee7ae8946b5593
? Your Twilio Auth Token for your Twilio Project: [hidden]
[DEBUG] -- BEGIN Twilio API Request --
[DEBUG] GET https://api.twilio.com/2010-04-01/Accounts/AC40cd61a06e07ba0df9ee7ae8946b5593.json
[DEBUG] User-Agent: @twilio/cli-core/4.4.2 (twilio-node/3.39.2, node.js v13.6.0, linux 5.4.8-arch1-1 x64, login)
[DEBUG] -- END Twilio API Request --
[DEBUG] response.statusCode: 200
[DEBUG] response.headers: {"date":"Sat, 18 Jan 2020 06:03:58 GMT","content-type":"application/json; charset=utf-8","content-length":"2259","connection":"close","last-modified":"Sat, 18 Jan 2020 03:48:27 +0000","twilio-concurrent-requests":"1","etag":"ea44e9c38c1a0d6941198acdc47edadf","twilio-request-id":"RQa2e9d833c6e84450a7bb09aa819c38a2","twilio-request-duration":"0.031","access-control-allow-origin":"*","access-control-allow-headers":"Accept, Authorization, Content-Type, If-Match, If-Modified-Since, If-None-Match, If-Unmodified-Since","access-control-allow-methods":"GET, POST, DELETE, OPTIONS","access-control-expose-headers":"ETag","access-control-allow-credentials":"true","x-powered-by":"AT-5000","x-shenanigans":"none","x-home-region":"us1","x-api-domain":"api.twilio.com","strict-transport-security":"max-age=31536000"}
[DEBUG] -- BEGIN Twilio API Request --
[DEBUG] POST https://api.twilio.com/2010-04-01/Accounts/AC40cd61a06e07ba0df9ee7ae8946b5593/Keys.json
[DEBUG] Form data:
[DEBUG] {"FriendlyName":"twilio-cli for lukario45 on gen-mc"}
[DEBUG] User-Agent: @twilio/cli-core/4.4.2 (twilio-node/3.39.2, node.js v13.6.0, linux 5.4.8-arch1-1 x64, login)
[DEBUG] -- END Twilio API Request --
[DEBUG] response.statusCode: 201
[DEBUG] response.headers: {"date":"Sat, 18 Jan 2020 06:03:58 GMT","content-type":"application/json; charset=utf-8","content-length":"248","connection":"close","twilio-concurrent-requests":"1","twilio-request-id":"RQ261ffae6284240ecb9e435a20fddb866","twilio-request-duration":"0.057","access-control-allow-origin":"*","access-control-allow-headers":"Accept, Authorization, Content-Type, If-Match, If-Modified-Since, If-None-Match, If-Unmodified-Since","access-control-allow-methods":"GET, POST, DELETE, OPTIONS","access-control-expose-headers":"ETag","access-control-allow-credentials":"true","x-powered-by":"AT-5000","x-shenanigans":"none","x-home-region":"us1","x-api-domain":"api.twilio.com","strict-transport-security":"max-age=31536000"}
[DEBUG] {"sid":"SKaa8615709d93ea689c081c9a4bb30c66","friendlyName":"twilio-cli for lukario45 on gen-mc","dateCreated":"2020-01-18T06:03:58.000Z","dateUpdated":"2020-01-18T06:03:58.000Z","secret":"VgglL80id1MQ9M8py4FHTVQ67sm2gXWh"}
libsecret-Message: 05:52:57.987: Remote error from secret service: org.freedesktop.DBus.Error.UnknownMethod: No such interface ?org.freedesktop.Secret.Collection? on object at path /org/freedesktop/secrets/collection/login
 » twilio-cli encountered an unexpected error. To report this issue, execute the command with the "-l debug" flag, then copy the output to a new issue here: https://github.com/twilio/twilio-cli/issues
[DEBUG] No such interface “org.freedesktop.Secret.Collection” on object at path /org/freedesktop/secrets/collection/login
[DEBUG] Error: No such interface “org.freedesktop.Secret.Collection” on object at path /org/freedesktop/secrets/collection/login`

**Comment by childish-sambino** [comment]
Duplicates #123 

Check there for the resolution.
