### ISSUE TITLE
local flask app not receiving incoming twilio sms messages

### ISSUE THREAD

**Issue by yenniejun** [twilio/twilio-cli#164]
### Issue Summary
A summary of the issue and the environment in which it occurs. If suitable, include the steps required to reproduce the bug. Please feel free to include screenshots, screencasts, or code examples.

### Steps to Reproduce
I am working on a very basic flask app to receive SMS, and to respond based on the content of the text that is received.

I have already tested to make sure that I can purely send (not worrying about the content that is received) messages. However, now, not even that is working when I send a text to that number.

In one window I am running
`twilio phone-numbers:update "+xxxxxxxxxxx" --sms-url="http://localhost:5000/sms"`

In the other I am running my `run.py` script which litreally just looks like this

### Code Snippet
```python
@app.route("/sms", methods=['GET', 'POST'])
def incoming_sms():
    print("hello")
    """ Get the incoming message the user sent our Twilio number """
    resp = MessagingResponse()

    # Add a text message
    msg = resp.message("The Robots are coming! Head for the hills!")

    return str(resp)
```

Not even printing the "hello" message in the debugger.

I am wondering if the issue is with the configuration settings I have with the Twilio console, but I am not sure... The reason I wonder this is because if I hit the localhost address from my browser, I am able to hit the debugger.

I copied the ngrok tunnel public URL and put it https://www.twilio.com/console/phone-numbers/xxxxidxxxxx under "A message comes in." I also put the pubilc url it https://www.twilio.com/console/sms/services/xxxxxxiexxxx as well under "Send an incoming message webhook" under inbound settings. Not sure if I had to set both of those up, because I wasn't really sure.

### Exception/Log
No exceptions at all! No error. Nothing happens.

### Technical details:
* twilio-python version: twilio-cli/1.11.0 linux-x64 node-v12.16.1
* python version: Python 3.7.7
I am on Windows Subsystem for linux (ubuntu)

**Comment by thinkingserious** [comment]
Hello @yenniejun,

I was unable to produce this issue, here are the steps I took:
1. Here is the Python/Flask code I used:

```python
# /usr/bin/env python
# Download the twilio-python library from twilio.com/docs/libraries/python
from flask import Flask, request
from twilio.twiml.messaging_response import MessagingResponse

app = Flask(__name__)

@app.route("/handle_sms", methods=['GET', 'POST'])
def sms_ahoy_reply():
    """Respond to incoming messages with a friendly SMS."""
    # Start our response
    resp = MessagingResponse()

    # Add a message
    resp.message("Ahoy! Thanks so much for your message.")

    return str(resp)

if __name__ == "__main__":
    app.run(debug=True)
```
2. I ran the above code using `python run.py`
3. In another terminal I ran `twilio phone-numbers:update +XXXXXXXXXXX --sms-url http://localhost:5000/handle_sms` (this step automatically creates the ngrok tunnel for you)
4. I sent a text message to +XXXXXXXXXXX and received the reply "Ahoy! Thanks so much for your message."
5. I see `127.0.0.1 - - [03/Apr/2020 15:06:11] "POST /handle_sms HTTP/1.1" 200 -` in my local Flask log.

Note that I did not make any modifications to the console.

Some things to check:
1. Please verify the steps above with the steps you executed
2. Perhaps your [Windows firewall](https://docs.microsoft.com/en-us/windows/wsl/faq#why-do-i-not-have-internet-access-from-wsl) is blocking the inbound traffic, please check your firewall settings

I hope that helps, thanks!

With best regards,

Elmer

**Comment by yenniejun** [comment]
hi @thinkingserious 
Thanks for your reply! I think there had been something mis-configured in the Twilio console. In the end I couldn't figure it out and ended up creating a new account! With the default settings of the new account and the same code, I did not have any issues. I will close this issue.
