### ISSUE TITLE
npm run deploy:twilio-cli --- error

### ISSUE THREAD

**Issue by gavrilovwm** [twilio/twilio-cli#176]
### Issue Summary
When trying to do anything with twilio-cli - I get errno 1 error
TRYED IT IN MY OWN APP VERSION AND DEFAULT FROM GITHUB REPOSITORY

### Steps to Reproduce
1. npm i
2. npm install -g twilio-cli
3. twilio plugins:install @twilio-labs/plugin-rtc
4. twilio login
5. npm run build
6. npm run deploy:twilio-cli / npm run deploy:twilio-cli -- --override / twilio rtc:apps:video:view / twilio rtc:apps:video:delete

### Exception/Log
```
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! twilio-video-app-react@0.1.0 deploy:twilio-cli: `cross-env REACT_APP_SET_AUTH=passcode npm run build && twilio rtc:apps:video:deploy --authentication=passcode --app-directory ./build "--override"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the twilio-video-app-react@0.1.0 deploy:twilio-cli script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\AA\AppData\Roaming\npm-cache\_logs\2020-04-24T09_22_10_557Z-debug.log
```

**Comment by childish-sambino** [comment]
Since this is an issue with the plugin, do you mind creating an issue [here](https://github.com/twilio-labs/plugin-rtc/issues)?
