### ISSUE TITLE
Question: How can we connect twilio-cli generate urls to autopilot?

### ISSUE THREAD

**Issue by muchriss** [twilio/twilio-cli#180]
### Question
After deploying the CLI provides a set of functions URLs labeled as protected. When copying one of those functions URLs to an Autopilot task, the task doesn't seem to run. 
How can we connect the functions URLs generated by twilio-cli to an Autopilot module?

### Steps to Reproduce
1. Deploy your app
2. Copy one of the urls generate
3. Go to Autopilot and generate a task
4. The action should be "redirect", copy that url there.
5. Build the model and simulate it.
6. Result: nothing happens.

### Technical details:
* twilio-cli version: 2.0.1
* node version: 10.17.0

**Comment by childish-sambino** [comment]
Recommend checking the [debugger](https://www.twilio.com/console/debugger) for any autopilot errors.
