### ISSUE TITLE
Error code 20001 from Twilio: At least one Function Version or Asset Version is required for Build.

### ISSUE THREAD

**Issue by KayBeSee** [twilio/twilio-cli#215]
### Issue Summary
I cannot build a service I created using the CLI. I keep getting `Error code 20001 from Twilio: At least one Function Version or Asset Version is required for Build.`

### Steps to Reproduce
1. Create a service
2. Create a function
3. Upload function
4. Create a function version
5. Create an asset
6. Upload asset
7. Create an asset version
8. Try to build

### Technical details:
* twilio-cli version: twilio-cli/2.8.0 darwin-x64 node-v14.5.0
* node version:
* Command output with debug logging enabled (adding `-l debug` to the end of the command):
```
 ~ twilio api:serverless:v1:services:builds:create --service-sid ZS9f5739fe06ac3259c589c5f8108cbbd6 -l debug
[DEBUG] Config File: /Users/kevinmulcrone/.twilio-cli/config.json
[DEBUG] Using profile: kbc-test
[DEBUG] Found command "api:serverless:v1:services:builds:create" plugin: twilio-cli
[DEBUG] Found keytar version in "@twilio/cli-core" dependencies: ^6.0.1
[DEBUG] Schema for "service-sid": {"type":"string"}
[DEBUG] Provided flags: {"service-sid":"ZS9f5739fe06ac3259c589c5f8108cbbd6","cli-log-level":"debug","properties":"sid,status,dateCreated","skip-parameter-validation":false,"cli-output-format":"columns"}
[DEBUG] domainName=serverless, path=/v1/Services/{ServiceSid}/Builds, actionName=create
[DEBUG] pathNode=ServiceSid, value=ZS9f5739fe06ac3259c589c5f8108cbbd6
[DEBUG] -- BEGIN Twilio API Request --
[DEBUG] post https://serverless.twilio.com/v1/Services/ZS9f5739fe06ac3259c589c5f8108cbbd6/Builds
[DEBUG] Custom HTTP Headers:
[DEBUG] User-Agent: @twilio/cli-core/5.9.0 (twilio-api-client/5.9.0, node.js v14.5.0, darwin 19.5.0 x64, api:serverless:v1:services:builds:create)
[DEBUG] -- END Twilio API Request --
[DEBUG] response.statusCode: 400
[DEBUG] response.headers: {"date":"Thu, 20 Aug 2020 23:53:36 GMT","content-type":"application/json; charset=utf-8; charset=utf-8","content-length":"170","connection":"close","twilio-request-id":"RQaa3247a259844dd98783d0eea94935be","twilio-request-duration":"0.038","access-control-allow-origin":"*","access-control-allow-headers":"Accept, Authorization, Content-Type, If-Match, If-Modified-Since, If-None-Match, If-Unmodified-Since","access-control-allow-methods":"GET, POST, DELETE, OPTIONS","access-control-expose-headers":"ETag","access-control-allow-credentials":"true","x-powered-by":"AT-5000","x-shenanigans":"none","x-home-region":"us1","x-api-domain":"serverless.twilio.com","strict-transport-security":"max-age=31536000"}
 » Error code 20001 from Twilio: At least one Function Version or Asset Version is required for Build. See https://www.twilio.com/docs/errors/20001 for more info.
[DEBUG] TwilioCliError: Error code 20001 from Twilio: At least one Function Version or Asset Version is required for Build. See https://www.twilio.com/docs/errors/20001 for more info.
    at CliRequestClient.request (/usr/local/Cellar/twilio/2.8.0/libexec/node_modules/@twilio/cli-core/src/services/cli-http-client.js:98:15)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async OpenApiClient.request (/usr/local/Cellar/twilio/2.8.0/libexec/node_modules/@twilio/cli-core/src/services/open-api-client.js:57:22)
    at async TwilioApiClient.create (/usr/local/Cellar/twilio/2.8.0/libexec/node_modules/@twilio/cli-core/src/services/twilio-api/twilio-client.js:48:22)
    at async NewCommandClass.run (/usr/local/Cellar/twilio/2.8.0/libexec/src/base-commands/twilio-api-command.js:39:22)
    at async NewCommandClass._run (/usr/local/Cellar/twilio/2.8.0/libexec/node_modules/@oclif/command/lib/command.js:43:20)
    at async Config.runCommand (/usr/local/Cellar/twilio/2.8.0/libexec/node_modules/@oclif/config/lib/config.js:173:24)
    at async Main.run (/usr/local/Cellar/twilio/2.8.0/libexec/node_modules/@oclif/command/lib/main.js:27:9)
    at async Main._run (/usr/local/Cellar/twilio/2.8.0/libexec/node_modules/@oclif/command/lib/command.js:43:20)
```

I have function and assets with versions as displaying in the API section and I can retrieve them/list them from the CLI. Any ideas?
<img width="961" alt="Screen Shot 2020-08-20 at 5 52 17 PM" src="https://user-images.githubusercontent.com/1429113/90836954-e6886580-e30d-11ea-98c6-4934299a65b5.png">

**Comment by childish-sambino** [comment]
Looks like you're missing the function and/or asset version(s) from your command. At least one of them is required. E.g.,
```
twilio api:serverless:v1:services:builds:create --service-sid ZS9f5739fe06ac3259c589c5f8108cbbd6 --function-versions ZN291...
```

**Comment by KayBeSee** [comment]
That worked! Thank you.

Just a heads up, I don't think the docs specify that you need to add a function version or asset version.

I was following this: https://www.twilio.com/docs/runtime/functions-assets-api/api/build?code-sample=code-fetch-build&code-language=Node.js&code-sdk-version=3.x

I tried running the code in the example and it gave me the same error. I didn't see a function/asset version in the example code and figured that building would build everything under that service-sid.

**Comment by childish-sambino** [comment]
I've created an internal ticket to look at updating the documentation (ref _SCP-82_).

**Comment by KayBeSee** [comment]
Hey Sam, the [docs](https://www.twilio.com/docs/runtime/functions-assets-api/api/deployment) for deploying also don't include having a build-sid which is necessary I believe.

You can run `twilio api:serverless:v1:services:environments:deployments:create --service-sid ZSxxxx --environment-sid ZExxxx` without the build-sid though and it won't error. I did this and was getting "RestException [Error]: Environment already has requested deployment." but the app wasn't in the URL of the `environment-url/function-url`

I also noticed in my dashboard that the build-sid was null on the environment which made me think I might have to specify that again when deploying. 
<img width="756" alt="Screen Shot 2020-08-24 at 4 56 28 PM" src="https://user-images.githubusercontent.com/1429113/91104329-c537ba00-e62a-11ea-9173-f9a823f3430e.png">

**Comment by childish-sambino** [comment]
Awesome! I've linked the internal ticket to this issue so the added info should help.

**Comment by FlyBooks** [comment]
> Hey Sam, the [docs](https://www.twilio.com/docs/runtime/functions-assets-api/api/deployment) for deploying also don't include having a build-sid which is necessary I believe.
> 
> You can run `twilio api:serverless:v1:services:environments:deployments:create --service-sid ZSxxxx --environment-sid ZExxxx` without the build-sid though and it won't error. I did this and was getting "RestException [Error]: Environment already has requested deployment." but the app wasn't in the URL of the `environment-url/function-url`
> 
> I also noticed in my dashboard that the build-sid was null on the environment which made me think I might have to specify that again when deploying.
> <img alt="Screen Shot 2020-08-24 at 4 56 28 PM" width="756" src="https://user-images.githubusercontent.com/1429113/91104329-c537ba00-e62a-11ea-9173-f9a823f3430e.png">
> 
> I was able to deploy after specifying the build-sid and it looks like things are working!

where i could find enviroment-sid?
