### ISSUE TITLE
Error: Flag --cli-log-level expects a value

### ISSUE THREAD

**Issue by lat34** [twilio/twilio-cli#228]
Error: Flag --cli-log-level expects a value

**Comment by eshanholtz** [comment]
This error means you have to provide a log level value. If you run your command with `--help` at the end, you can see the options for this flag. The default log level is `info`, but for additional information we often recommend using `debug`. For example:
```
twilio phone-numbers:list --cli-log-level debug
```
or,
```
twilio phone-numbers:list -l debug
```
