### ISSUE TITLE
Unable to obtain authorization for this operation

### ISSUE THREAD

**Issue by AlexRentheria** [twilio/twilio-cli#231]
[DEBUG] -- BEGIN Twilio API Request --
[DEBUG] POST https://api.twilio.com/2010-04-01/Accounts/ACCOUNT_SID/Keys.json
[DEBUG] Form data:
[DEBUG] FriendlyName=twilio-cli%20for%20root%20on%20iMac.local
[DEBUG] Custom HTTP Headers:
[DEBUG] User-Agent: @twilio/cli-core/5.12.0 (twilio-node/3.52.0, node.js v15.2.1, darwin 19.3.0 x64, login)
[DEBUG] -- END Twilio API Request --
[DEBUG] response.statusCode: 201
[DEBUG] response.headers: {"date":"Tue, 24 Nov 2020 17:42:02 GMT","content-type":"application/json; charset=utf-8","content-length":"258","connection":"close","twilio-concurrent-requests":"1","twilio-request-id":"RQdaf3d3d189ce4becb7638452e9f70174","twilio-request-duration":"0.042","access-control-allow-origin":"*","access-control-allow-headers":"Accept, Authorization, Content-Type, If-Match, If-Modified-Since, If-None-Match, If-Unmodified-Since","access-control-allow-methods":"GET, POST, DELETE, OPTIONS","access-control-expose-headers":"ETag","access-control-allow-credentials":"true","x-powered-by":"AT-5000","x-shenanigans":"none","x-home-region":"us1","x-api-domain":"api.twilio.com","strict-transport-security":"max-age=31536000"}
[DEBUG] Found command "login" plugin: twilio-cli

twilio-cli encountered an unexpected error. To report this issue, execute the command with the "-l debug" flag, then copy the output to a new issue here: "https://github.com/twilio/twilio-cli/issues"

[DEBUG] Unable to obtain authorization for this operation.
[DEBUG] Error: Unable to obtain authorization for this operation.

* twilio-cli version: twilio-cli/2.13.0 darwin-x64
* node version: v15.2.1

**Comment by eshanholtz** [comment]
What was the original command you ran that produced this log output?
