### ISSUE TITLE
twilio cli deploy keeps using the api key that I have deleted

### ISSUE THREAD

**Issue by tzhang318** [twilio/twilio-cli#236]
I'm just starting to test twilio video.

I'm running into authentication issues from twilio cli.

I'm using a mac and have stored the twilio account sid and twilio auth token in my .bash_profile file.

printenv | grep TWILIO

> TWILIO_ACCOUNT_SID=AC***********
> TWILIO_AUTH_TOKEN=03************

I'm trying to run this comand:

twilio serverless:deploy

here's the output: 

> Deploying functions & assets to the Twilio Runtime
> 
> Account		SK5c8ebd79********************
> Token		rGM2****************************
> Service Name	green-1212
> Environment	dev
> Root Directory	/Users/timzhang/invoke/v2-main/green-1212
> Dependencies
> Env Variables
> 
> ✖ Failed Deployment
> 
> │ ERROR Failed API Request 20003
> │
> │ Authenticate
> │
> │ More info: https://www.twilio.com/docs/errors/20003

The issue for me is: the account api sid here the cli using is wrong. I have deleted that api key from twilio console. 
How can I let my cli know to use the credentials from my .bash_profile? Or how can I let my cli use an api_key, api_secret that I created from the twilio console? Or how to reset my environment variables such that twilio cli would pick up the new credentials?

Thanks.

Tim

**Comment by eshanholtz** [comment]
Do you have the TWILIO_API_KEY and TWILIO_API_SECRET environment variables set as well? The CLI will use those by default.

**Comment by tzhang318** [comment]
Yes, I did that before. But just found out there's a .env file in the serverless example code that's using the stale variables.
