### ISSUE TITLE
not able to create new sub-account with twilio profiles:create command

### ISSUE THREAD

**Issue by git-santosh** [twilio/twilio-cli#240]
I already have one account on DEV instance and l linked that to twilio-cli.
when i tried to add another account (STG) I am getting an error when i execute the command
twilio profiles: create -l debug
![image](https://user-images.githubusercontent.com/6646963/105329054-bc0d4200-5bf6-11eb-928f-06af5ad9af9b.png)

**Comment by shwetha-manvinkurke** [comment]
Have you tried logging in again - `twilio login` using your stage credentials and then create a profile?

**Comment by git-santosh** [comment]
`twilio-login` does not worked then I preferred to go with profiles:create option.
Both are not working. Yes.. I am using my STG cred

**Comment by shwetha-manvinkurke** [comment]
Try `twilio profiles:create --region=stage`
