### ISSUE TITLE
Twilio-Login for CLI does not work as it gives unexpected error

### ISSUE THREAD

**Issue by dhivanpatel** [twilio/twilio-cli#245]
### Issue Summary
Twilio-login or twilio create profile spits out unexpected error, saying "name is not correct" after entering short hand identifier
System Info Below
twilio-cli/2.19.0 darwin-x64 node-v15.11.0

### Steps to Reproduce
1. Twilio-Login
2. enter auth and account keys
3. shorthand id

[DEBUG] -- BEGIN Twilio API Request --
[DEBUG] GET https://api.twilio.com/2010-04-01/Accounts/AC39e9a211d6030a4f27051c4f660eae22.json
[DEBUG] Custom HTTP Headers:
[DEBUG] User-Agent: @twilio/cli-core/5.19.0 (twilio-node/3.58.0, node.js v15.11.0, darwin 18.7.0 x64, login)
[DEBUG] -- END Twilio API Request --
[DEBUG] response.statusCode: 200
[DEBUG] response.headers: {"date":"Thu, 18 Mar 2021 01:01:55 GMT","content-type":"application/json; charset=utf-8","content-length":"2244","connection":"close","last-modified":"Wed, 17 Mar 2021 19:58:05 +0000","twilio-concurrent-requests":"1","etag":"af80873dd4f5ac80bd9b42df83c8355f","twilio-request-id":"RQ6f3d3006c254151af9757591f97b1251","twilio-request-duration":"0.033","access-control-allow-origin":"*","access-control-allow-headers":"Accept, Authorization, Content-Type, If-Match, If-Modified-Since, If-None-Match, If-Unmodified-Since","access-control-allow-methods":"GET, POST, DELETE, OPTIONS","access-control-expose-headers":"ETag","access-control-allow-credentials":"true","x-powered-by":"AT-5000","x-shenanigans":"none","x-home-region":"us1","x-api-domain":"api.twilio.com","strict-transport-security":"max-age=31536000"}
? Shorthand identifier for your profile: Dhivan
[DEBUG] -- BEGIN Twilio API Request --
[DEBUG] POST https://api.twilio.com/2010-04-01/Accounts/AC39e9a211d6030a4f27051c4f660eae22/Keys.json
[DEBUG] Form data:
[DEBUG] FriendlyName=twilio-cli%20for%20dhivanpatel%20on%20Dhivans-MBP.attlocal.net
[DEBUG] Custom HTTP Headers:
[DEBUG] User-Agent: @twilio/cli-core/5.19.0 (twilio-node/3.58.0, node.js v15.11.0, darwin 18.7.0 x64, login)
[DEBUG] -- END Twilio API Request --
[DEBUG] response.statusCode: 201
[DEBUG] response.headers: {"date":"Thu, 18 Mar 2021 01:01:57 GMT","content-type":"application/json; charset=utf-8","content-length":"268","connection":"close","twilio-concurrent-requests":"1","twilio-request-id":"RQ16897424f668e5f0e23c163a1573945e","twilio-request-duration":"0.045","access-control-allow-origin":"*","access-control-allow-headers":"Accept, Authorization, Content-Type, If-Match, If-Modified-Since, If-None-Match, If-Unmodified-Since","access-control-allow-methods":"GET, POST, DELETE, OPTIONS","access-control-expose-headers":"ETag","access-control-allow-credentials":"true","x-powered-by":"AT-5000","x-shenanigans":"none","x-home-region":"us1","x-api-domain":"api.twilio.com","strict-transport-security":"max-age=31536000"}
[DEBUG] Found command "login" plugin: twilio-cli
 » twilio-cli encountered an unexpected error. To report this issue, execute the command with the "-l debug" flag, then copy the output to a new issue here: "https://github.com/twilio/twilio-cli/issues"
[DEBUG] The user name or passphrase you entered is not correct.
[DEBUG] Error: The user name or passphrase you entered is not correct.

**Comment by shwetha-manvinkurke** [comment]
@dhivanpatel Can you try doing [this](https://github.com/atom/node-keytar/issues/76#issuecomment-348813996) ?

**Comment by dhivanpatel** [comment]
@shwetha-manvinkurke That worked thank you!
