### ISSUE TITLE
twilio login fails

### ISSUE THREAD

**Issue by kwmartin** [twilio/twilio-cli#251]
<!--
Raspberry Pi 4B running 64-bit Ubuntu 20.04 recently upgraded

### Code Snippet
> twilio login
You can find your Account SID and Auth Token at https://www.twilio.com/console
 » Your Auth Token will be used once to create an API Key for future CLI access to your Twilio Account or Subaccount, and then forgotten.
? The Account SID for your Twilio Account or Subaccount: AC894de8d0898f03e4d5b5236795650b15
? Your Twilio Auth Token for your Twilio Account or Subaccount: [hidden]
? Shorthand identifier for your profile: twilioProfile
 » twilio-cli encountered an unexpected error. To report this issue, execute the command with the "-l debug" flag, then copy the output to a new issue here: "https://github.com/twilio/twilio-cli/issues"
> twilio-cli -l debug
twilio-cli: command not found
> twilio -l debug
 ›   Error: command -l not found
> 
```

**Comment by JenniferMah** [comment]
Hi @kwmartin can you include some more information around how twilio login is failing by running `twilio login -l debug` and posting the output in your reply? Thanks!

**Comment by kylegrussell** [comment]
I'm having the same error...here is my output. Using iTerm with zsh on a Mac.

[DEBUG] {"message":"unable to get local issuer certificate","name":"Error","stack":"Error: unable to get local issuer certificate\n    at TLSSocket.onConnectSecure (_tls_wrap.js:1506:34)\n    at TLSSocket.emit (events.js:315:20)\n    at TLSSocket._finishInit (_tls_wrap.js:948:8)\n    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:706:12)","config":{"url":"https://api.twilio.com/2010-04-01/Accounts/ACe666219d034a59ddd844b5dbe961be63.json","method":"get","headers":{"Accept":"application/json","User-Agent":"@twilio/cli-core/5.23.0 (twilio-node/3.62.0, node.js v12.18.0, darwin 19.4.0 x64, login)","Accept-Charset":"utf-8","Connection":"close","Authorization":"Basic QUNlNjY2MjE5ZDAzNGE1OWRkZDg0NGI1ZGJlOTYxYmU2MzplNzA3N2U2Y2QyNGRkZjVmYTdkY2NkNDAxMzZmN2QyNQ=="},"transformRequest":[null],"transformResponse":[null],"timeout":30000,"xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN","maxContentLength":-1,"maxBodyLength":-1,"maxRedirects":0},"code":"UNABLE_TO_GET_ISSUER_CERT_LOCALLY"}

**Comment by shwetha-manvinkurke** [comment]
@kylegrussell we are currently investigating the issue you ran into. Will keep you posted when we have a resolution. 

[Internal tracking](https://issues.corp.twilio.com/browse/DI-1397)

**Comment by shwetha-manvinkurke** [comment]
Hi @kylegrussell there is a doc that is still WIP regarding cert issues but here are a few things you can try to resolve the issue:

- Ensure you have the latest version of the Twilio CLI installed. You can upgrade your Twilio CLI installation by following the steps located here.

- Ask your company's Information Technology department to provide you with the CA certificates that are being used and store them in a directory on your hard drive.

- Set the environment variable TWILIO_CA_BUNDLE to the path of the .pem or .ca-bundle file that you saved earlier.

If the above steps do not work, we recommend that you work with your company's Information Technology department to add "*.twilio.com" domains to their "allow-list" so that TLS traffic to Twilio will not be proxied.

**Comment by charan678** [comment]
@nathan-kinship Can you please create new issue and add complete debug log, environment details, cli version and any other additional information which can help us to resolve the issue. Please try to use latest version of Twilio cli and for debug logs you can use this command : twilio login -l debug

**Comment by nathan-kinship** [comment]
Literally all of that information is right here in this ticket.

**Comment by nathan-kinship** [comment]
For future Googlers:

1) It will take weeks of back-and-forth with Twilio support before anyone tells you that Twilio engineers do not test this tool against anything newer than Node 16. If you have anything newer than 16, this tool will probably never completely work. Why that's neither in their dependencies nor their documentation is anybody's guess. 

2) Get a CA bundle from your favorite CA bundle extractor and tell Node to use it in addition to whatever you might have from your OS or IT department with something like `export NODE_EXTRA_CA_CERTS=~/.twilio-cli/cacert-2022-10-11.pem` The `TWILIO_CA_BUNDLE` variable has absolutely nothing to do with anything and, as far as I can tell, is ignored. 

With these two things done, you should be able to clear the hurdle and run the tool.
