### ISSUE TITLE
Twilio CLI: Does not support media / Twilio Live calls

### ISSUE THREAD

**Issue by jezell** [twilio/twilio-cli#335]
### Issue Summary

Twilio CLI does not appear to support the new Live api

### Steps to Reproduce

twilio api:media

### Technical details:
* twilio-cli version: 2.33.0
* node version: v17.0.1
* Command output with debug logging enabled (adding `-l debug` to the end of the command):
```
Error: command api:media not found
```

**Comment by kridai** [comment]
Hi @jezell. Thanks for reaching out. The current Twilio CLI version 2.33.0 does not contains these changes due latest twilio cli-core changes not available in twilio-cli. We are working on this issue and should be fixed in the next release this Thursday.

**Comment by kridai** [comment]
Hi @jezell, this should be fixed as part of the latest twilio-cli release, version 2.34.0. please update to the latest version

**Comment by jezell** [comment]
Thanks. Look's like it's there now
