### ISSUE TITLE
Flex Dev plugin - profiles broken

### ISSUE THREAD

**Issue by deshartman** [twilio/twilio-cli#372]
### Issue Summary
Flex Dev plugin cannot find profiles when starting, since upgrading to v3 cli

### Steps to Reproduce
1. twilio profiles:list
```
ID          Account SID                         Active
main        AC75xx  false 
Flex    AC2f5xx  true  
```
2. twilio flex:plugins:start

### Exception/Log
```
 » Could not find profile.
 » To create the profile, run:

  twilio profiles:create

Alternatively, twilio-cli can use credentials stored in environment variables:

# OPTION 1 (recommended)
export TWILIO_ACCOUNT_SID=your Account SID from twil.io/console
export TWILIO_API_KEY=an API Key created at twil.io/get-api-key
export TWILIO_API_SECRET=the secret for the API Key

# OPTION 2
export TWILIO_ACCOUNT_SID=your Account SID from twil.io/console
export TWILIO_AUTH_TOKEN=your Auth Token from twil.io/console

Once these environment variables are set, a twilio-cli profile is not required and you may skip the "login" step.
```

### Technical details:
* twilio-cli version: twilio-cli/3.0.0 darwin-x64 node-v14.18.1
* node version: v14.18.1
* Command output with debug logging enabled (adding `-l debug` to the end of the command):
```
[DEBUG] Config File: /Users/dhartman/.twilio-cli/config.json
[DEBUG] TwilioCliError: To create the profile, run:

  twilio profiles:create

Alternatively, twilio-cli can use credentials stored in environment variables:

# OPTION 1 (recommended)
export TWILIO_ACCOUNT_SID=your Account SID from twil.io/console
export TWILIO_API_KEY=an API Key created at twil.io/get-api-key
export TWILIO_API_SECRET=the secret for the API Key

# OPTION 2
export TWILIO_ACCOUNT_SID=your Account SID from twil.io/console
export TWILIO_AUTH_TOKEN=your Auth Token from twil.io/console

Once these environment variables are set, a twilio-cli profile is not required and you may skip the "login" step.
    at reportUnconfigured (/Users/dhartman/.twilio-cli/node_modules/@twilio-labs/plugin-flex/node_modules/@twilio/cli-core/src/base-commands/twilio-client-command.js:33:13)
    at FlexPluginsStart.run (/Users/dhartman/.twilio-cli/node_modules/@twilio-labs/plugin-flex/node_modules/@twilio/cli-core/src/base-commands/twilio-client-command.js:39:7)
    at async FlexPluginsStart.run (/Users/dhartman/.twilio-cli/node_modules/@twilio-labs/plugin-flex/dist/sub-commands/flex-plugin.js:243:9)
    at async FlexPluginsStart._run (/Users/dhartman/.twilio-cli/node_modules/@twilio-labs/plugin-flex/node_modules/@twilio/cli-core/node_modules/@oclif/command/lib/command.js:43:20)
    at async Config.runCommand (/usr/local/lib/node_modules/twilio-cli/node_modules/@oclif/config/lib/config.js:173:24)
    at async Main.run (/usr/local/lib/node_modules/twilio-cli/node_modules/@oclif/command/lib/main.js:27:9)
    at async Main._run (/usr/local/lib/node_modules/twilio-cli/node_modules/@oclif/command/lib/command.js:43:20)
```

**Comment by Sindhura3** [comment]
@deshartman thanks for raising the issue, this is known. We are awaiting a major release from flex plugin to fix the problem. Until then, please use an older version of CLI (like 2.36.1)

**Comment by otaviofff** [comment]
I'm not sure what the "flex" plugin is. But I can see that `twilio:autopilot` doesn't work anymore, as it can't load `twilio:profiles`. 

Is it the same bug? What's the ETA?

Thanks.

**Comment by Sindhura3** [comment]
@otaviofff It is the same bug. For autopilot, we have [raised a PR on that repo](https://github.com/dabblelab/twilio-cli-autopilot-plugin/pull/52) and awaiting a merge and release.

**Comment by otaviofff** [comment]
Thanks for the update. Looks like the `dabblelab/twilio-cli-autopilot-plugin` package may not be active anymore though. Last commit from 2020.

Why doesn't the official `twilio-cli` package support `autopilot`? It's unsual that Twilio would have a GA product with no CLI support. What's going on there?

**Comment by onuzbee** [comment]
Thanks for reaching out @otaviofff. Autopilot plugin is community owned as of today. 

The [PR](https://github.com/dabblelab/twilio-cli-autopilot-plugin/pull/52) has been merged, and can expect the release to npm post testing in a couple of days. Thank You!

**Comment by shrutiburman** [comment]
@deshartman, @otaviofff, Flex has done a major release which is compatible with CLI. Please upgrade to CLI [latest](https://github.com/twilio/twilio-cli/releases/tag/3.1.0) version and try, we'll wait here for your confirmation.
Thanks!

**Comment by beebzz** [comment]
Closing due to lack of confirmation, feel free to reopen if more help is needed.
