### ISSUE TITLE
Apt install fails, unexpected size. 

### ISSUE THREAD

**Issue by mikewoodld** [twilio/twilio-cli#383]
`E: Failed to fetch https://twilio-cli-prod.s3.amazonaws.com/apt/Packages.xz  File has unexpected size (1016 != 676). Mirror sync in progress? [IP: 52.217.228.225 443]`

**Comment by charan678** [comment]
Thanks for reporting this issue. 

We are able to reproduce this issue and we will try to fix it ASAP, meanwhile you can install twilio-cli using debian file. Reference: [Debian](https://www.twilio.com/docs/twilio-cli/getting-started/install#deb-file)

**Comment by charan678** [comment]
This issue has been resolved.
