### ISSUE TITLE
Assisted upgrade of file-type available

### ISSUE THREAD

**Issue by jsfix-updater** [twilio/twilio-cli#421]
Version 15 of file-type is available.
  The JSFIX tool can help you through the update process (**Ensuring that all the necessary changes are made to your project in the process**).
  Use this [link](https://jsfix.live/jsfix/https%3A%2F%2Fgithub.com%2Ftwilio%2Ftwilio-cli) to start the upgrade process (_It's completely free_).
  
  Leave a comment on this issue if you have any questions or concerns.

**Comment by mtorp** [comment]
Thanks @shrutiburman !
Let us know if you have any questions or run into problems.
