### ISSUE TITLE
Lookup V2 request issues error message saying `"validationResults" is not a valid property name`

### ISSUE THREAD

**Issue by robinske** [twilio/twilio-cli#504]
### Issue Summary
The API call still works, it just prints an annoying message before the wanted output.

Seems [similar to am issue from 2021](https://github.com/twilio/twilio-cli/issues/246) but I haven't been able to track down a specific discrepancy in API definitions.

### Steps to Reproduce

Using CLI v5.0+:

```
twilio api:lookups:v2:phone-numbers:fetch --phone-number +14159929960
```

The output will include ` » "validationResults" is not a valid property name.`

### Technical details:
* twilio-cli version: 5.3.3, but confirmed it's an issue on 5.0.0 too (Lookup V2 is not available via the CLI before 5.0)
* node version: v19.6.0
* Command output with debug logging enabled (adding `-l debug` to the end of the command):
```
[DEBUG] Config File: /Users/krobinson/.twilio-cli/config.json
[DEBUG] Using profile: ${TWILIO_ACCOUNT_SID}/${TWILIO_AUTH_TOKEN}
[DEBUG] Schema for "phone-number": {"type":"string"}
[DEBUG] Provided flags: {"phone-number":"+14159929960","cli-log-level":"debug","cli-output-format":"columns","silent":false,"skip-parameter-validation":false,"properties":"callingCountryCode,phoneNumber,countryCode,valid,validationResults,nationalFormat"}
[DEBUG] domainName=lookups, path=/v2/PhoneNumbers/{PhoneNumber}, actionName=fetch
[DEBUG] pathNode=PhoneNumber, value=%2B14159929960
[DEBUG] -- BEGIN Twilio API Request --
[DEBUG] get https://lookups.twilio.com/v2/PhoneNumbers/%2B14159929960
[DEBUG] Custom HTTP Headers:
[DEBUG] User-Agent: twilio-cli/5.3.3 @twilio/cli-core/7.5.3 (darwin x64) twilio-api-client/7.5.3 api:lookups:v2:phone-numbers:fetch
[DEBUG] -- END Twilio API Request --
[DEBUG] response.statusCode: 200
[DEBUG] response.headers: {"date":"Wed, 08 Feb 2023 19:00:18 GMT","content-type":"application/json; charset=utf-8","content-length":"433","connection":"close","twilio-request-id":"RQf926c8985efb7cecc83dd7839af23e66","twilio-request-duration":"0.018","access-control-allow-origin":"*","access-control-allow-headers":"Accept, Authorization, Content-Type, If-Match, If-Modified-Since, If-None-Match, If-Unmodified-Since, Idempotency-Key","access-control-allow-methods":"GET, POST, DELETE, OPTIONS","access-control-expose-headers":"ETag","access-control-allow-credentials":"true","x-powered-by":"AT-5000","twilio-concurrent-requests":"1","x-shenanigans":"none","x-home-region":"us1","x-api-domain":"lookups.twilio.com","strict-transport-security":"max-age=31536000"}
[DEBUG] No conversion function for "phone-number" schema format
```

**Comment by bnb** [comment]
FWIW running the same command I'm getting the same error.

**Comment by kridai** [comment]
Hi @robinske, Thanks for reaching out. This is something that needs to be updated from the api side. We have reached out to the team. +1 to the issue will help us move it higher in the priority list. 
meanwhile other way would be to pass the property flag with the properties you need displayed. for eg
`twilio api:lookups:v2:phone-numbers:fetch --phone-number [+14159929960](tel:+14159929960) --properties=callingCountryCode,phoneNumber,countryCode,valid,nationalFormat`

**Comment by sbansla** [comment]
@robinske 
Below mentioned output was coming because validationResults was not set to any value. This has been removed. Fix should be available in next release.
» "validationResults" is not a valid property name.

**Comment by childish-sambino** [comment]
Fixed by https://github.com/twilio/twilio-cli-core/commit/b00131887a91ac51226901f75c3062154b631182#diff-411381779985366649534b3f7805166b4e9f73f186af4e9e2b20d450805f27bb
