### ISSUE TITLE
 TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))

### ISSUE THREAD

**Issue by deshartman** [twilio/twilio-cli#527]
### Issue Summary
Trying to generate a token for chat. This used to work and have also tried a different laptop and versions.

```
% twilio token:chat --identity=des --chat-service-sid=IS8xxxxxxxx

    TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
```

I have updated OSX to Ventura 13.3.1 and Twilio cli and Twilio plugin are up to date.
twilio-cli/5.5.0 darwin-x64 node-v16.15.0

**Comment by kridai** [comment]
Hi @deshartman , I tried reproducing this issue for node-v16.15.0 for twilio-cli/5.5.0, but couldn't. I see you have mentioned twilio plugins are update, could please confirm the version of `@twilio-labs/plugin-token` you have. You could run the command `twilio plugins` to know the version

**Comment by Chrispassold** [comment]
Hi, I'm having the same issue, but using `twilio token:video --identity=<identity>`.
I have this versions installed:

twilio-cli/5.14.0 darwin-arm64 node-v20.6.1
@twilio-labs/plugin-token 4.0.0
