### ISSUE TITLE
Unexpected arguments: --tags

### ISSUE THREAD

**Issue by mosiman** [twilio/twilio-cli#553]
### Issue Summary
The [documentation](https://www.twilio.com/docs/sms/api/message-resource#create-a-message-resource) implies a `--tags` argument is available, and I believe this was added in version 5.14 of `twilio-cli` according to the release notes.

However, when I try to create a message with tags, the CLI states that the `--tags` argument is not expected. I've also tried curl'ing the endpoint and wasn't able to get it to recognize `tags`. Is it possible this hasn't been implemented on the server yet?

### Steps to Reproduce
1. Pull the latest docker image and confirm it is version 5.14
2. Try to create a message with a json object passed to the "tags" flag.
3. Observe the error message

### Code Snippet
```
docker run -it --rm twilio/twilio-cli bash
root@f2791fd8d968:/twilio# twilio version
twilio-cli/5.14.0 linux-x64 node-v18.16.0
root@f2791fd8d968:/twilio# twilio api:core:messages:create --messaging-service-sid "<messaging service sid>" --body "testing from twilio cli with tags" --to "<my phone number>" --tags '{"foo": "bar", "bar": 123}' -l debug
 ›   Error: Unexpected arguments: --tags, {"foo": "bar", "bar": 123}
 ›   See more help with --help
```

### Technical details:
* twilio-cli version: 5.14.0 (docker)
* node version: v18.16.0 (docker)

**Comment by AsabuHere** [comment]
Hi @mosiman,
I was reviewing the parameters that can be provided to create a message, from documentation and I could not locate tags as a valid parameter. Can you point out where exactly is this mentioned in https://www.twilio.com/docs/sms/api/message-resource#create-a-message-resource

Thanks,
Athira

**Comment by mosiman** [comment]
Oh, it seems to be gone now. But, at the time the docs looked something like this

![twilio_send_sms_tags](https://github.com/twilio/twilio-cli/assets/16958825/9ccaf4c2-87c8-4994-a428-e910ba639b90)

Since it's no longer documented, I suppose this is no longer an issue.

However, there still seems to be some lingering references to tags. See for example, the latest Go SDK: https://github.com/twilio/twilio-go/blob/dabadd4c76df49852a1c07738bc0d5b6c7761de3/rest/api/v2010/model_api_v2010_message.go#L56

**Comment by AsabuHere** [comment]
Hi @mosiman, Tags feature was added as a public feature before and was updated in docs too. Now with a later commit, this tags feature was reverted and the visibility has been changed to private and maturity as preview(earlier it was beta). So there will be references in the libraries even now, but wont be available as a public feature. For the features/options that is supported now, please check using the --help option in CLI
Eg : twilio api:core:messages:create --help
Closing this issue since its no longer part of documentation
