### ISSUE TITLE
[Video API] The flag --room-sid always prints "Missing required flag room-sid"

### ISSUE THREAD

**Issue by kNoAPP** [twilio/twilio-cli#556]
### Issue Summary
When executing the following commands, the CLI always returns the error:
```
 »   Error: The following error occurred:
 »     Missing required flag room-sid
 »   See more help with --help
 ```
 
 Commands:
 ```
 twilio api video:v1:rooms:participants:list --room-sid="RM20b23b3ec526d485b90a7aa9a016985a"
 twilio api video:v1:rooms:participants:list --room-sid RM20b23b3ec526d485b90a7aa9a016985a
 twilio api video:v1:rooms:participants list --room-sid="RM20b23b3ec526d485b90a7aa9a016985a"
 twilio api video:v1:rooms:participants list --room-sid RM20b23b3ec526d485b90a7aa9a016985a
```

### Steps to Reproduce
Run any of the above commands. Ensure a profile has been set prior. You may need to use a different, valid room sid.

### Code Snippet
None

### Exception/Log
None

### Technical details:
* twilio-cli version: twilio-cli/5.5.0 win32-x64 
* node version: node-v16.19.1
* Command output with debug logging enabled (adding `-l debug` to the end of the command):
```
twilio api video:v1:rooms:participants:list --room-sid="RM20b23b3ec526d485b90a7aa9a016985a" -l debug
 »   Error: The following error occurred:
 »     Missing required flag room-sid
 »   See more help with --help
```

**Comment by kNoAPP** [comment]
Still an issue.

**Comment by spalmertwilio** [comment]
Issue Verified.  The parameter that is missing is 'status'  With the options of 'in-progress' or 'completed' as seen in https://www.twilio.com/docs/video/api/participants?code-sample=code-retrieve-a-list-of-connected-participants&code-language=curl&code-sdk-version=json

**Comment by kNoAPP** [comment]
Thanks @spalmertwilio. Even then, according to the documentation you provided, 'status' should be optional.

**Comment by spalmertwilio** [comment]
Yes, you are correct.  We now have an bug in our backlog for this issue.
