### ISSUE TITLE
APT installation failing due to unsigned repository

### ISSUE THREAD

**Issue by BOTPaul** [twilio/twilio-cli#610]
### Issue Summary
We're currently trying to install the Twilio CLI via the APT install instructions.
After setting up the keychain, the process fails at the
`sudo apt update` step with the following error:

```
GPG error: https://twilio-cli-prod.s3.amazonaws.com/apt  InRelease: The following signatures were invalid: EXPKEYSIG DBE46296BE30F0B0 Twilio (Twilio CLI) <team-interfaces@twilio.com>
The repository 'https://twilio-cli-prod.s3.amazonaws.com/apt  InRelease' is not signed.
```

### Steps to Reproduce
Follow the installation instructions on https://www.twilio.com/docs/twilio-cli/quickstart#install-the-twilio-cli for APT
It fails during the update step.

**Comment by BOTPaul** [comment]
It looks like the signature is now valid again. 
Any idea what caused the repository to be unsigned yesterday?

**Comment by tiwarishubham635** [comment]
Hello! We were in the process of updating the keys that we use in signing the debian packages. For some time, the public key file was mismatching. Probably that's the reason why they showed "unsigned" yesterday
