### ISSUE TITLE
Listing Messaging Services

### ISSUE THREAD

**Issue by kuryaki** [twilio/twilio-cli#74]
▶ twilio api:messaging:v1:services:list -l debug

[DEBUG] Config File: /Users/kuryaki/.twilio-cli/config.json
[DEBUG] Using project: ${TWILIO_ACCOUNT_SID}/${TWILIO_AUTH_TOKEN}
[DEBUG] Provided flags: {"cli-log-level":"debug","properties":"sid,friendlyName,dateCreated","cli-output-format":"columns"}
[DEBUG] domainName=messaging, path=/v1/Services, actionName=list
[DEBUG] -- BEGIN Twilio API Request --
[DEBUG] get https://messaging.twilio.com/v1/Services
[DEBUG] User-Agent: @twilio/cli-core/2.0.3 (twilio-api-client/2.0.3, node.js v12.5.0, darwin 18.6.0 x64, api:messaging:v1:services:list)
[DEBUG] -- END Twilio API Request --
[DEBUG] response.statusCode: 200
[DEBUG] response.headers: {"date":"Tue, 16 Jul 2019 20:59:28 GMT","content-type":"application/json; charset=utf-8","content-length":"62491","connection":"close","twilio-concurrent-requests":"1","twilio-request-id":"XXXX","twilio-request-duration":"0.076","access-control-allow-origin":"*","access-control-allow-headers":"Accept, Authorization, Content-Type, If-Match, If-Modified-Since, If-None-Match, If-Unmodified-Since","access-control-allow-methods":"GET, POST, DELETE, OPTIONS","access-control-expose-headers":"ETag","access-control-allow-credentials":"true","x-powered-by":"AT-5000","x-shenanigans":"none","x-home-region":"us1","x-api-domain":"messaging.twilio.com","strict-transport-security":"max-age=31536000"}
[DEBUG] -- BEGIN Twilio API Request --
[DEBUG] get https://messaging.twilio.comhttps://messaging.twilio.com/v1/Services?PageSize=50&Page=1&PageToken=XXXX
[DEBUG] User-Agent: @twilio/cli-core/2.0.3 (twilio-api-client/2.0.3, node.js v12.5.0, darwin 18.6.0 x64, api:messaging:v1:services:list)
[DEBUG] -- END Twilio API Request --
 » twilio-cli encountered an unexpected error. To report this issue, execute the command with the "-l debug" flag, then copy the output to a new issue here: https://github.com/twilio/twilio-cli/issues
[DEBUG] getaddrinfo ENOTFOUND messaging.twilio.comhttps
[DEBUG] Error: getaddrinfo ENOTFOUND messaging.twilio.comhttps
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:60:26)

**Comment by childish-sambino** [comment]
Fixed by https://github.com/twilio/twilio-cli-core/pull/46
