### ISSUE TITLE
Error on twilio phone-numbers:update

### ISSUE THREAD

**Issue by Ethanb00** [twilio/twilio-cli#94]
OS:Win10

C:\Users\[redact]>twilio phone-numbers:update +1[redact] --sms-url=http://localhost:4040 -l debug
[DEBUG] Config File: C:\Users\[redact]\.twilio-cli\config.json
[DEBUG] Using profile: AC143d094fbc8ef8fc781423285788acaa
[DEBUG] -- BEGIN Twilio API Request --
[DEBUG] GET https://api.twilio.com/2010-04-01/Accounts/AC143d094fbc8ef8fc781423285788acaa/IncomingPhoneNumbers.json
[DEBUG] Querystring:
[DEBUG] {"PhoneNumber":"+1[redact]"}
[DEBUG] User-Agent: @twilio/cli-core/3.0.2 (twilio-node/3.33.3, node.js v10.16.1, win32 10.0.18362 x64, phone-numbers:update)
[DEBUG] -- END Twilio API Request --
[DEBUG] response.statusCode: 200
[DEBUG] response.headers: {"date":"Mon, 05 Aug 2019 20:20:51 GMT","content-type":"application/json; charset=utf-8","content-length":"1578","connection":"close","twilio-concurrent-requests":"1","twilio-request-id":"RQe0306e360458403ea3b69a288858260c","twilio-request-duration":"0.084","access-control-allow-origin":"*","access-control-allow-headers":"Accept, Authorization, Content-Type, If-Match, If-Modified-Since, If-None-Match, If-Unmodified-Since","access-control-allow-methods":"GET, POST, DELETE, OPTIONS","access-control-expose-headers":"ETag","access-control-allow-credentials":"true","x-powered-by":"AT-5000","x-shenanigans":"none","x-home-region":"us1","x-api-domain":"api.twilio.com","strict-transport-security":"max-age=31536000"}
 » twilio-cli encountered an unexpected error. To report this issue, execute the command with the "-l debug" flag, then copy the output to a new issue here: https://github.com/twilio/twilio-cli/issues
[DEBUG] Cannot read property 'err' of undefined
[DEBUG] TypeError: Cannot read property 'err' of undefined
    at NumberUpdate.createTunnel (C:\Users\[redact]\AppData\Roaming\npm\node_modules\twilio-cli\src\commands\phone-numbers\update.js:80:48)
    at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by childish-sambino** [comment]
Not sure what the underlying issue is, but we're choking on the error that's being thrown. I'll look at fixing the debug so we can actually see the contents of the error.

**Comment by Ethanb00** [comment]
thanks! 

other potential relevant things:
had ngrok already installed
ngrok was running

(I'm at signal if you need to see IRL)

**Comment by childish-sambino** [comment]
Unfortunately I'm not at SIGNAL. I've posted a PR which should help debug this issue. You can pull the branch to your local if you want to debug right now. Otherwise, it will be in the next release.

**Comment by Ethanb00** [comment]
Aha! Ok, I'm seeing the actual error now:

`Error: connect ECONNREFUSED 127.0.0.1:4041`

Do I need to manually open that port to the CLI? I wasn't prompted to allow it network access. Is there something I missed doing?

**Comment by childish-sambino** [comment]
Probably a firewall issue.

**Comment by Ethanb00** [comment]
I'll poke around a bit. I'm running the regular windows firewall and utilities would typically request firewall access (like, coincidentally TwilioQuest does). Thanks for the help.

**Comment by childish-sambino** [comment]
You mentioned having ngrok already installed and running. Any issues with tunneling the same port that you're trying to tunnel in the CLI?

**Comment by Ethanb00** [comment]
Yeah, so I think that was the key. Shutting down ngrok allows the CLI command to run successfully. 

And then the CLI runs the ngrok session. 

It would be nice for the CLI to tap into my running ngrok session to perform what it needs to do.

**Comment by childish-sambino** [comment]
Did some investigating and have a better understanding of the error now. `ngrok` attempts to find the first available port in the range _4040-4049_ to run the inspector and accept tunnel creation requests. The error you see (`Error: connect ECONNREFUSED 127.0.0.1:4041`) indicates that the first available port in the range was `4041` since you had another instance of `ngrok` already running and it was using the default `4040` port. But, the CLI failed to connect to the newly spawned process on port `4041` for some reason. Maybe there's a conflict in that you have some other local app already bound to port `4041` and it was causing a conflict.

Recommend investigating if there is some other local apps bound to ports in the _4040-4049_ range and adjust those if possible. In general, don't use these ports for ngrok tunneling to avoid conflicts.

Local app port conflicts aside, I haven't had any issues in running multiple instances of `ngrok`. I'd prefer not trying to re-use existing `ngrok` instances as its life exists outside the context of the CLI. A hard quit on the CLI would not allow us to properly terminate `ngrok` or drop the tunnel.

Appreciate your help in providing more details. I've opened a couple issues against the `ngrok` lib to help with debugging such issues.

**Comment by Ethanb00** [comment]
Thanks for the insights and the deeper dive on the potential ngrok/twilio CLI conflict. 

using TCPView from SysInternals, I replicated the environment from the other day (i.e. ngrok running separately via exe) and the only app showing up in that port range is ngrok. on 4040. next closest is dropbox on 4099 and 4100.

![image](https://user-images.githubusercontent.com/5893479/62652468-50ef8300-b910-11e9-8d21-b54980acbe09.png)

**Comment by childish-sambino** [comment]
Since you were trying to create tunnel to local port `4040` (`--sms-url=http://localhost:4040`), what service framework were you using? And was it binding to any other ports? (Still, should not tunnel `4040` since `ngrok` tries to use it for its own purposes)

**Comment by Ethanb00** [comment]
Flask on 5000

**Comment by childish-sambino** [comment]
Do you still see the original issue now with `ngrok` running? And does it have any active tunnels?

**Comment by Ethanb00** [comment]
Ok, so:

1. I started the flask app, (super basic hello world script). 
2. I started ngrok with ngrok http 5000
3. I ran `twilio phone-numbers:update +1[redact]  --sms-url=http://localhost:4040 -l debug` and got 
` » Error: connect ECONNREFUSED 127.0.0.1:4041`
and this is what the TCPView looked like for a brief moment
![image](https://user-images.githubusercontent.com/5893479/62655148-3fa97500-b916-11e9-84b4-bfdbfc74b5e7.png)

4. Then I ran  `twilio phone-numbers:update +1[redact]  --sms-url=http://localhost:4040 -l debug` again and got a new error: ` » remote gone away`

Sorry for not being able to deliver better new :(

**Comment by childish-sambino** [comment]
Eep, that's concerning. Maybe the spawned `ngrok` process is failing to start correctly. The `ngrok` debug issue I filed should help to know what's going on.

Are you able to start a second `ngrok` process outside the CLI? Curious if that succeeds.

**Comment by Ethanb00** [comment]
ah ha! Ok, so. No, I could not start a second grok session because (i assume) I am on a free account. 

 I think that means the takeaway here is that free-level grok users can't have existing grok sessions open when working with the CLI because they're restricted to 1 active grok session. 

I don't know how much of an edge case this is, but...yeah, sounds like you tracked down the root cause! I'm not if there's a way to check for existing grok sessions, validate if it is a free session and if so, error out with a notice that session needs to come down before CLI can proceed.

**Comment by childish-sambino** [comment]
Hmm, I'm on a free account and have many instances running. The docs indicate I shouldn't be able to. Either way, we need better messaging to indicate the process failed to start.

**Comment by childish-sambino** [comment]
Fixed by #100
