### ISSUE TITLE
twilio phone-numbers:update issue

### ISSUE THREAD

**Issue by Money-Map-Press** [twilio/twilio-cli#97]
This is the debug output 

[DEBUG] Config File: /Users/cchambers/.twilio-cli/config.json
[DEBUG] Using profile: cory
[DEBUG] -- BEGIN Twilio API Request --
[DEBUG] GET https://api.twilio.com/2010-04-01/Accounts/ACe66f201ae4c434aa11b795de867b38f2/IncomingPhoneNumbers.json
[DEBUG] Querystring:
[DEBUG] {"PhoneNumber":"+14104497866"}
[DEBUG] User-Agent: @twilio/cli-core/3.0.2 (twilio-node/3.33.3, node.js v10.16.0, darwin 17.7.0 x64, phone-numbers:update)
[DEBUG] -- END Twilio API Request --
[DEBUG] response.statusCode: 200
[DEBUG] response.headers: {"date":"Tue, 06 Aug 2019 17:06:54 GMT","content-type":"application/json; charset=utf-8","content-length":"1499","connection":"close","twilio-concurrent-requests":"1","twilio-request-id":"RQ552c74c088aa4a75a17734c8aec66ad3","twilio-request-duration":"0.174","access-control-allow-origin":"*","access-control-allow-headers":"Accept, Authorization, Content-Type, If-Match, If-Modified-Since, If-None-Match, If-Unmodified-Since","access-control-allow-methods":"GET, POST, DELETE, OPTIONS","access-control-expose-headers":"ETag","access-control-allow-credentials":"true","x-powered-by":"AT-5000","x-shenanigans":"none","x-home-region":"us1","x-api-domain":"api.twilio.com","strict-transport-security":"max-age=31536000"}
 » twilio-cli encountered an unexpected error. To report this issue, execute the command with the "-l debug" flag, then copy the output to a new issue here: https://github.com/twilio/twilio-cli/issues
[DEBUG] Cannot read property 'err' of undefined
[DEBUG] TypeError: Cannot read property 'err' of undefined
    at NumberUpdate.createTunnel (/usr/local/Cellar/twilio/1.4.1/libexec/src/commands/phone-numbers/update.js:80:48)
    at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by Money-Map-Press** [comment]
If I POST to this endpoint (http://localhost:8767/sms)  in POSTMAN I get the "twilio-cli is amazing!" response so the web server is running.

**Comment by childish-sambino** [comment]
Similar to #94 

Thinking it's a firewall issue, but haven't been able to confirm yet.

**Comment by Money-Map-Press** [comment]
OK thank you. I thought so maybe also but wanted to create this ticket just in case.

**Comment by Money-Map-Press** [comment]
I'm also at SIGNAL if that helps

**Comment by childish-sambino** [comment]
Unfortunately I'm not at SIGNAL.

Could you try pulling branch from #95 and installing that? It would at least give you a better error message. Not sure when the next release will be that includes that fix.

**Comment by childish-sambino** [comment]
Updated #94 after some investigation. There's a few things that can be done better in `twilio-cli` as well as the `ngrok` lib to help diagnose this issue and I've created issues already.

In the mean time, please check if there's another instance of `ngrok` running on your local machine or anything locally bound to ports `4040-4049`.

**Comment by childish-sambino** [comment]
Fixed by #100
